feat: Add new option --exclude-name
mousabaker/poetry-plugin-up pull request #31
Opened 2023-10-06 19:44 UTC by MikeZaharov

2023-10-06 19:50 UTC, MikeZaharov commented
* Resolves [(🎁) An option to exclude a list of dependencies #9](https://github.com/MousaZeidBaker/poetry-plugin-up/issues/9)
Added a new option --exclude-name

2023-10-09 06:57 UTC, MikeZaharov commented
@MousaZeidBaker Hi! I would be so grateful if you release it asap

2023-10-09 07:01 UTC, MousaZeidBaker commented
> Author

Hi, there are unresolved comments.

2023-10-09 07:24 UTC, MikeZaharov commented
> > Author
> 
> Hi, there are unresolved comments.

I don't see any comments(

2023-10-09 08:38 UTC, MousaZeidBaker requested changes

2023-10-09 08:38 UTC, mousabaker commented on src/poetry_plugin_up/command.py
> +        exclude_names: Optional[List[str]] = None,
> Note that this is not the same concept as an optional argument, which is one that has a default. An optional argument with a default does not require the Optional qualifier on its type annotation just because it is optional

https://docs.python.org/3/library/typing.html

2023-10-09 08:38 UTC, mousabaker commented on src/poetry_plugin_up/command.py
> +            long_name="exclude-name",
Maybe name it just `exclude`? What do you think?

2023-10-09 08:38 UTC, mousabaker commented on src/poetry_plugin_up/command.py
> +        exclude_names: Optional[List[str]] = None,
We can just set the default value to an empty list

`List[str]] = []`

2023-10-09 09:06 UTC, MikeZaharov commented on src/poetry_plugin_up/command.py
> +            long_name="exclude-name",
I borrowed it from your previous project. But exclude look good for me

2023-10-09 09:17 UTC, MikeZaharov commented on src/poetry_plugin_up/command.py
> +        exclude_names: Optional[List[str]] = None,
Thanks, done

2023-10-09 09:17 UTC, MikeZaharov commented on src/poetry_plugin_up/command.py
> +            long_name="exclude-name",
Done

2023-10-09 10:29 UTC, merged